server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Acces-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/credit/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/file/**
        - id: evaluate-service
          uri: lb://evaluate-service
          predicates:
            - Path=/api/evaluate/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/state/**
        - id: totalcost-service
          uri: lb://totalcost-service
          predicates:
            - Path=/api/totalcost/**

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expone todos los endpoints de Actuator
  endpoint:
    gateway:
      enabled: true # Habilita los endpoints relacionados con Gateway
