server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: lb://user_service
          predicates:
            - Path=/user/**
        - id: credit_service
          uri: lb://credit_service
          predicates:
            - Path=/credit/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: evaluate_service
          uri: lb://evaluate_service
          predicates:
            - Path=/evaluate/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/tracking/**
        - id: totalcost_service
          uri: lb://totalcost_service
          predicates:
            - Path=/cost/**
