apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-deployment
  labels:
    app: cost-deployment
spec:
  selector:
    matchLabels:
      app: cost-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: cost-deployment
    spec:
      containers:
        - name: kubernetes-cost
          image: milovlobos/totalcost-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-costdb
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_COST
              valueFrom:
                configMapKeyRef:
                  name: postgres-costdb
                  key: POSTGRES_DB_COST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cost-service
  labels:
    app: cost-service
spec:
  selector:
    app: cost-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer