apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
  labels:
    app: file-deployment
spec:
  selector:
    matchLabels:
      app: file-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: file-deployment
    spec:
      containers:
        - name: kubernetes-file
          image: milovlobos/file-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-filedb
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_FILE
              valueFrom:
                configMapKeyRef:
                  name: postgres-filedb
                  key: POSTGRES_DB_FILE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  selector:
    app: file-deployment
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: LoadBalancer