apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-costdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_COST: totalcost
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-creditdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_CREDIT: credit
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-evaluationdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_EVALUATION: evaluate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-filedb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_FILE: file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-trackingdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_TRACKING: state
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-userdb
data:
  POSTGRES_DB_HOST: postgres 
  POSTGRES_DB_USER: usuario
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  script.sql: |
    CREATE DATABASE totalcost;
    CREATE DATABASE credit;
    CREATE DATABASE evaluate;
    CREATE DATABASE file;
    CREATE DATABASE state;
    CREATE DATABASE usuario;