FROM openjdk:17
ARG JAR_FILE=demo/target/totalcost_service-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} totalcost_service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","/totalcost_Sservice-0.0.1-SNAPSHOT.jar"]